trainer:
  total_timesteps: 5_000_000          # OPTIONAL: INCREASE THE TRAINING STEPS
  model_save_freq: 1_000_000
  log_freq: 10_000
  gradient_steps: 30
  env_steps: 250
  train_seed: 10
  eval_seed: 100
env:
  name: myoarm-v0
  n_parallel: 4
  performance_curriculum: True
  performance_function: update_goal_threshold
save:
  project_name: student_project_myoarm
  run_name: test_10                      # TODO: CHANGE THE AGENT NAME HERE
wandb:
  flag: True
  entity: jhoncharaja
  tag: ['your_name_or_group_name', 'useful_tag']      # TODO: CHANGE THE TRAINING TAGS HERE

